default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    key_path = File.expand_path(File.basename(ENV["ASC_KEY_PATH"]), __dir__)
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: key_path
    )
    build_app(
      project: "GuandanApp.xcodeproj",
      scheme: "GuandanApp",
      export_method: "app-store",
      output_directory: "build/ipa",
      xcargs: "-allowProvisioningUpdates -authenticationKeyID #{ENV['ASC_KEY_ID']} -authenticationKeyIssuerID #{ENV['ASC_ISSUER_ID']} -authenticationKeyPath #{key_path}"
    )
    upload_to_testflight(api_key: api_key, skip_waiting_for_build_processing: true)
  end
end
